import { PERMISSIONS, type Permission } from "./permissions";

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  FIELD_REP: "field_rep",
  HR: "hr",
  FINANCE: "finance",
  AUDITOR: "auditor",
  VIEWER: "viewer",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

const ALL: Permission[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL,
  [ROLES.ADMIN]: ALL.filter((p) => p !== PERMISSIONS.AUDIT_VIEW),
  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VISIT_VIEW,
    PERMISSIONS.VISIT_APPROVE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORT_VISIT_VIEW,
    PERMISSIONS.REPORT_SALES_VIEW,
    PERMISSIONS.REPORT_EXPENSE_VIEW,
  ],
  [ROLES.FIELD_REP]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.VISIT_VIEW,
    PERMISSIONS.VISIT_CREATE,
    PERMISSIONS.DOCTOR_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.HOLIDAY_VIEW,
    PERMISSIONS.SALES_VIEW,
  ],
  [ROLES.HR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_MANAGE,
    PERMISSIONS.HOLIDAY_VIEW,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.REPORT_EMPLOYEE_VIEW,
    PERMISSIONS.REPORT_LEAVE_VIEW,
  ],
  [ROLES.FINANCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EXPENSE_VIEW,
    PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORT_EXPENSE_VIEW,
    PERMISSIONS.REPORT_SALES_VIEW,
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORT_LEAVE_VIEW,
    PERMISSIONS.REPORT_SALES_VIEW,
    PERMISSIONS.REPORT_VISIT_VIEW,
    PERMISSIONS.REPORT_EXPENSE_VIEW,
    PERMISSIONS.REPORT_EMPLOYEE_VIEW,
  ],
  [ROLES.VIEWER]: [PERMISSIONS.DASHBOARD_VIEW],
};

export function permissionsForRoles(roles: Role[]): Set<Permission> {
  const set = new Set<Permission>();
  for (const r of roles) for (const p of ROLE_PERMISSIONS[r] ?? []) set.add(p);
  return set;
}